module.exports = Object.freeze({

    PROJECT_STATUS_INACTIVE: 1,
    PROJECT_STATUS_PLANNING: 2,
    PROJECT_STATUS_VALIDATION: 3,
    PROJECT_STATUS_PROPOSAL: 4,
    PROJECT_STATUS_IN_PROGRESS: 5,
    PROJECT_STATUS_ENDED: 6,
    PROJECT_STATUS_ABANDONED: 7,
    PROJECT_STATUS_BANNED: 10,

})
