version: "3.0"
services:

  moonfish-frontend:
    container_name: moonfish-frontend
    restart: always # Always restart the container if it stops
    build:
      context: ../front-end/
    ports:
      - 80:5000
    depends_on: # Wait on databases before start
      - moonfish-backend

  moonfish-backend:
    container_name: moonfish-backend
    restart: always # Always restart the container if it stops
    build:
      context: ../back-end/
      target: dev
    volumes:
      - ../back-end:/app
    command: sh -c "sleep 60 && npm run ${EXPRESS_CMD}" # 'npm run start' : for production mode,
                                                        # 'npm run dev' : for development mode, etc
    ports:
      - 3000:3000
    depends_on: # Wait on databases before start
      - mariadb
      - neo4j
    environment:
      NODE_ENV: ${NODE_ENV} # 'development' or 'production' mode
      DEBUG: nodejs-docker-express:*

  mariadb:
    image: mariadb
    container_name: moonfish-mariadb
    restart: always # Always restart the container if it stops
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: moonfish
      MARIADB_USER: moonfish
      MARIADB_PASSWORD: Ebqcqzh79qeRedPb

  phpmyadmin:
    image: phpmyadmin
    container_name: moonfish-phpmyadmin
    restart: unless-stopped # Similar to always, except that when the container is stopped
                            # it is not restarted even after Docker daemon restarts.
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  neo4j:
    image: neo4j
    container_name: moonfish-neo4j
    restart: always # Always restart the container if it stops
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/wwjPLuSVVKFZ3QRa #  username (must be neo4j) / password
      NEO4J_dbms_logs_debug_level: DEBUG

volumes:
  mariadb-data: #  This is where all MariaDB data will be stored,
                # even if container is restarted, data will be there.

networks:
  default: #  This is the shared network between the fourth containers
    name: moonfish
