version: "3.0"
services:

  moonfish-backend:
    container_name: moonfish-backend
    restart: unless-stopped # Similar to always, except that when the container is stopped it is not restarted even after Docker daemon restarts.
    build:
      context: ../back-end/
      target: dev
    volumes:
      - ../back-end:/app
    command: npm run start # 'npm run dev' : for development mode
    ports:
      - 3000:3000
    depends_on:
      - mariadb
      - neo4j
    environment:
      NODE_ENV: production # 'development' : for production mode
      DEBUG: nodejs-docker-express:*

  mariadb:
    image: mariadb
    container_name: moonfish-mariadb
    restart: always # Always restart the container if it stops
    ports:
      - 3306:3306
    command: "mysqld --init-file /data/application/init.sql"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./mariadb/init.sql:/data/application/init.sql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: moonfish
      MARIADB_USER: "moonfish"
      MARIADB_PASSWORD: "moonfishPwd"

  phpmyadmin:
    image: phpmyadmin
    container_name: moonfish-phpmyadmin
    restart: unless-stopped # Similar to always, except that when the container is stopped it is not restarted even after Docker daemon restarts.
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  neo4j:
    image: neo4j
    container_name: moonfish-neo4j
    restart: always # Always restart the container if it stops
    hostname: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    environment:
      NEO4J_dbms_logs_debug_level: DEBUG

volumes:
  mariadb-data: #  This is where all db data will be stored, even if container is restarted, data will be there.

networks:
  default:
    name: moonfish
