module.exports = Object.freeze({

    HOURS_TO_BLOCK: 2,
    ITEMS_LIMIT: 10,
    MAX_LOGIN_ATTEMPTS: 5,
    MAX_PROJECT_MARK: 5.0,
    MIN_PROJECT_MARK: 0.1,
    NB_OF_APPLIES_FOR_100_PERCENT: 10,
    NB_OF_TAGS_FOR_100_PERCENT: 5,
    REF_PROJECTS_LIMIT: 3

})
