module.exports = Object.freeze({

    HOURS_TO_BLOCK: 2,
    MAX_LOGIN_ATTEMPTS: 5,
    SALT_FACTOR: 5,
    ITEMS_LIMIT: 10,
    NB_OF_TAGS_FOR_100_PERCENT: 3,
    NB_OF_APPLIES_FOR_100_PERCENT: 5,
    MIN_PROJECT_MARK: 0.1,
    MAX_PROJECT_MARK: 5.0,

})
