module.exports = Object.freeze({

    RELATION_APPLIES: 'APPLIES',
    RELATION_ARBITRATES: 'ARBITRATES',
    RELATION_DEVELOPS: 'DEVELOPS',
    RELATION_IS_MEMBER_OF: 'IS_MEMBER_OF',
    RELATION_MANDATES: 'MANDATES',

})
